### PR TITLE
Update Registrar.php to populate email field

### PR DESCRIPTION
**Pull request by nicklee1990**
Adding email field during signup to enable email verification from Parse.

### CODE REVIEW

**Comment by hipsterjazzbo** [comment]
I'm not sure this is the best way to do this. I think what we need is a better way to make the field names you're passing in to the registrar be configurable, to properly handle all the valid ways you can use them in Parse. Thoughts?

**Comment by nicklee1990** [comment]
Yeah I agree, I did this as a 'bare minimum' change based on the fact you're calling out email as mandatory in the Registrar validator which I thought implied you'd be using the email as the username so it seemed logical to do this change. Thinking about it though, it needs a change to give a bit more flexibility.

Perhaps in the meantime a documentation update clarifying extending the Registrar and User classes would help?

**Comment by ghost** [comment]
Can we merge this as a temporary solution until we come up with something more general?

**Comment by hipsterjazzbo** [comment]
Sure why not.

**Pull request merged**
