### PR TITLE
Improve session storage

### PR DESCRIPTION
**Pull request by hipsterjazzbo**
This will need to be tested to make sure that:
- The change to accept Laravel 5.1.\* doesn't break anything
- The injecting of the session rather than using a facade doesn't break anything

### CODE REVIEW

**Comment by danjordan** [comment]
The default parse implementation stores all of it's session data as an array with a storageKey. I think it would be a good idea to do that here as well, otherwise you could be clearing all session data, when you actually only want to clear the parse session.

I can make a pull request if it helps?

**Comment by nicklee1990** [comment]
good point, pull request welcome! 

On a related note, I did notice the other day that calling Auth::logout() was not unsetting the ParseUser when I do ParseUser::getCurrentUser. I have to explicitly call ParseUser::logout() in my Auth Controller which isn't ideal - need to have a look at this as well

**Comment by danjordan** [comment]
I've actually written a different implementation of your UserProvider which returns an Illuminate\Auth\GenericUser instead of the ParseUser object. So far it seems to work with Facebook login/logout and normal credentials login/logout. I'll try to make a pull request for that as well.

**Comment by nicklee1990** [comment]
Tested and is working fine

**Comment by nicklee1990** [comment]
@danjordan did you get a chance to create a PR for your version of the UserProvider? It'd be good to see some sample code to see how you've done it

**Comment by danjordan** [comment]
Nah, I've been on holiday and I've stopped working on the project that required it :(

I'll see if I can have a look into it over the next few days and whack a pull request up next week.

**Pull request merged**
